import numpy as np

MAX_SPEED = 1.0
MIN_SPEED = -0.5
MAX_YAW_RATE = np.deg2rad(40.0)
MAX_ACCEL = 0.2
MAX_YAW_ACCEL = np.deg2rad(40.0)
DT = 0.1
PREDICT_TIME = 3.0

VELOCITY_RESOLUTION = 0.01
YAWRATE_RESOLUTION = np.deg2rad(1.0)

ARC_CENTER = [5.0, 5.0]
ARC_RADIUS = 10.0
ARC_TOTAL_STEPS = 500
ARC_START_ANGLE = 0.0
ARC_END_ANGLE = np.pi

DESIRED_RELATIVE_ANGLE = 0.0
GOAL_OFFSET_DIST = 2.0
GOAL_OFFSET_ANGLE = np.deg2rad(90)

POSITION_ERROR_COST_GAIN = 20.0
RELATIVE_ANGLE_COST_GAIN = 5.0
SPEED_COST_GAIN = 0.0

# === Lookahead Adjustment ===
LOOKAHEAD_DISTANCE_GAIN = 4.0
LOOKAHEAD_ANGLE_GAIN = 3.0
LOOKAHEAD_MIN = 0
LOOKAHEAD_MAX = 12